diamondmyracle/HW1

- cssForIndex.css
Starting the css file for index.html; so far only contains some starting comments for what we will be needing to implement and a bit of styling for the navbar of index.html
> Starting code for cssForIndex

- listings.css
- listings.html
I've gone and done some styling for the listing page. Listings should now appear as little boxes and whatnot. And they should be somewhat responsive to changes in screen size and whatnot.
> Listings page css

- index.html
added the subscription tier list
> Update index.html with Tier List

- index.html
FAQ section of the landing page.
> Faq section

- login.html
this is the login page and eventually will be the sign up page as well
> upload login.html

- index.html
now users can click in the navbar, it should take them to the pages
> added hyperlink to navbar

- login.css
- login.html
- signup.css
- signup.html
I've done styling for the login and signup pages.
> Login signup styling

- cssForIndex.css
I styled the navbar, and also started styling the header (by accident, I should have done that in a separate issue)
> Update cssForIndex.css (navbar + parts of the header)

- signup.css
- signup.html
> Added the ad (Issue #47)

- index.html
> added insta, x, linkedin hyperlinks

- index.html
- listings.html
- login.html
- signup.html
- timeline.html
I have added a line in all of the heads of the html files.
> Added preconnect (Issue #63)

- cssForIndex.css
- index.html
- listings.css
- listings.html
- login.css
- login.html
- signup.css
- signup.html
- timeline.html
I've made it so that they load in the head of the HTML, and also it's only loading 2 weights.
> Only 2 fonts (Issue #69)

- listings.css
- listings.html
- login.css
- signup.css
I did that, and I also made the border-radius work a bit better on the listings page.
> Edited text color (Issue #72)

- cssForIndex.css
Fixed the color contrast of disclaimer
> Changed color of disclaimer (Issue #86)

- index.html
> removed the video

- editlisting.php
- newlisting.css
- newlisting.php
Listing creation has been implemented.
> Implement listing creation

- newlisting.php
> Added some functionality to (Issue #140)

- editlisting.php
- login.php
- newlisting.php
> Implemented listing editing (Issue #154)

- editlisting.php
- newlisting.php
I've made it report to the user the requirements that haven't been met.
> Inform users of required fields listings

- listings.php
I fixed the issue. Changed it to $username
> Fixed it (Issue #169)

- listings.php
I made the button. For some reason, I could only get inline styling to work for it, so it's a bit jank for now.
> Made it (Issue #171)

- bootstrap.php
> Created bootstrap.php (Issue #185)

- baseController.php
I made the file as seen in the tutorial
> Created the baseController file (Issue #188)

- Controller/Api/ListingController.php
- Controller/Api/UserController.php
- index.php
- signup.php
> Comment out send output

- Controller/Api/UserController.php
- signup.php
I have done as the issue stated.
> JSONified (Issue #207)

- Controller/Api/UserController.php
- signup.php
As the name says, I've created the endpoint and moved validation. I also changed the code in UserController.php so that it sends proper JSON responses.
> Created endpoint and moved validation (Issue #211)

- signup.php
> Did the stuff from the issue (Issue #214)

- Controller/Api/UserController.php
- Model/UserModel.php
- login.php
- signup.php
I've made it so that the login functionality is restful. And also you're automatically signed in when you sign up.
> Made login restful (Issue #217)

- Model/Database.php
- newlisting.php
I fixed it. Although, for now, the image that is displayed is hard-coded.
> Fixed listing creation (Issue #219)

- Controller/Api/BaseController.php
- Controller/Api/ListingController.php
- Model/Database.php
- Model/ListingModel.php
- README.md
- editlisting.php
- inc/bootstrap.php
- index.php
- listings.php
- newlisting.php
> Revert and restful listings

- Model/ListingModel.php
- editlisting.php
- newlisting.php
> Altered the code to not generate random IDs (Issue #231)

- Controller/Api/ListingController.php
- Model/ListingModel.php
- editlisting.php
- listings.php
- signup.php
> Make editlisting restful

- viewlisting.php
I made it so that you're redirected to the login page when you try to submit a comment without being logged in.
> Redirect to login when posting comment and not signed in (Issue #260)

- viewlisting.css
- viewlisting.php
I made it so that the reply textbox and whatnot only shows up when you hit the reply button. I also changed a bit of the button styling.
> Only display textbox for comments when replying

- viewlisting.php
> Only show delete when op

- README.md
> Added the line (issue #275)

- viewlisting.css
- viewlisting.php
> Add comment date displayer

- editlisting.php
- viewlisting.css
- viewlisting.php
I made the style changes and updated the redirection link when you hit the save button.
> Made style changes and updated redirect (Issue #279)

- Controller/Api/CommentController.php
- Model/CommentModel.php
- upload.php
- viewlisting.css
- viewlisting.php
> Add comment edit functionality

- viewlisting.php
Fixed the bug. The delete was supposed to be a delete request, but it was always a post request.
> Solved the bug (Issue #292)

- Controller/Api/ListingController.php
- Model/ListingModel.php
- Model/UserModel.php
- README.md
- listings.php
- viewlisting.php
> Add buy functionality
